version: "3.7"

services: 
    redis:
        image: "redis:latest"
        ports: 
            - "26379:6379"
        restart: always
    mysql:
        image: "mysql:8.0.21"
        ports: 
            - "23306:3306"
        environment: 
            MYSQL_ROOT_PASSWORD: root1234
        restart: always
    flytest:
        build: .
        ports: 
            - "5000:5000"
        env_file: .env
        links: 
            - mysql:dbserver
            - redis:redisserver
        depends_on: 
            - mysql
            - redis