"""update

Revision ID: 5f02d062eab5
Revises: d343c646afac
Create Date: 2021-09-10 13:41:13.951473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f02d062eab5'
down_revision = 'd343c646afac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_profiler_measurements')
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.drop_index('ix_apscheduler_jobs_next_run_time')

    op.drop_table('apscheduler_jobs')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    op.create_table('flask_profiler_measurements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('startedAt', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('endedAt', mysql.DECIMAL(precision=10, scale=0), nullable=True),
    sa.Column('elapsed', mysql.DECIMAL(precision=6, scale=4), nullable=True),
    sa.Column('method', mysql.TEXT(), nullable=True),
    sa.Column('args', mysql.TEXT(), nullable=True),
    sa.Column('kwargs', mysql.TEXT(), nullable=True),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('context', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
